### ISSUE TITLE
As a guardian I would like to be able to delete pictograms I've uploaded so that I can remove wrongly uploaded / outdated pictograms

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#273]

**Comment by Lortemanden** [comment]
Where is the uploaded piktogram saved? We would like for there to be a distinkte between the ones we have uploaded and the ones users have uploaded, since we don´t have the rights to what they upload. 

Below is shown the pictogram seach screen where its possible to filter for if the guardian want to see all pictograms, the ones we provide or the ones the guardian has uploaded. There is a screen showing each filter setting. 
![image](https://user-images.githubusercontent.com/55434783/77746297-05175880-701d-11ea-9583-62b1a79dfcad.png)
![image](https://user-images.githubusercontent.com/55434783/77746315-0a74a300-701d-11ea-841b-4ce846f5051a.png)
![image](https://user-images.githubusercontent.com/55434783/77746326-0e082a00-701d-11ea-89d6-a17568dc45ca.png)

For the pictogram that the guardian has uploaded there is a delete button. The guardian should be able to delete the picogram he or she has uploaded. When the delete button is pressed a popup as shown below should popup. 
![image](https://user-images.githubusercontent.com/55434783/77746489-47409a00-701d-11ea-9742-dcd1b90c45ce.png)
