### ISSUE TITLE
As a guardian I want to be able to customize the amount of activities a citizen can view so that it fits their personal preference.

### ISSUE THREAD

**Issue by T-Dawq** [aau-giraf/weekplanner-OLDUI#346]
**Describe the solution you'd like**
The feature should only be available, if the citizen is limited to viewing one day at a time. The setting should be changed in the citizen settings as shown below.
![image](https://user-images.githubusercontent.com/55434783/77515137-4c181900-6e78-11ea-9fac-21b91d6d3188.png)

If one day is not selected the option to chose amount of activities should be grayed out like shown below. 
![image](https://user-images.githubusercontent.com/55434783/77515276-85e91f80-6e78-11ea-8e20-99cf9b5b657d.png)

If one activity is chosen the citizen's view should be changed to the below:
![image](https://user-images.githubusercontent.com/55434783/77516069-f9d7f780-6e79-11ea-81e4-1c7902979316.png)
The amount of activities the citizen can see should reflect the amount chosen in the settings. 
When the activity is done or canceled it should show the next not done activity. If there is no more not done activities from the current day it should not show activities from the next day. Instead it should show the latest activity with the activity done mark as shown below. 
![image](https://user-images.githubusercontent.com/55434783/78784355-7ce26d00-79a5-11ea-8297-864fae1ee373.png)

**Comment by Laexander** [comment]
Changes to the settings should also happen on the api_client and the web_api, as these do not have a option for number of activities to display

**Comment by Jaffenheimer** [comment]
Extending this issue, it should also be possible to view the day plan:

1. With an arrow indicating which activity that is currently active.
2. Being able to drag an item into a box (or something similar) for it to disappear.
3. With a picture of an employee indicating which employee that you are going to spend time with at the current activity, this should also be implement so that it can (if needed) follow the arrow.
