### ISSUE TITLE
We can't catch exceptions thrown by the web-api in the weekplanner

### ISSUE THREAD

**Issue by Lortemanden** [aau-giraf/weekplanner-OLDUI#349]
**Describe the bug**
We can't seem to catch a exception thrown from the web-api in the weekplanner

**To Reproduce**
1. Try to log in with a not valid log in
2. There is thrown a exception
3. Group 15 has tried to catch this exception in login_screen.dart but it does not seem to work

**Expected behavior**
The exception should be caught
**Actual behavior**
The exception can't be caught

**Screenshots**
![](https://cdn.discordapp.com/attachments/370998034336841728/692019380023722004/unknown.png)

**Comment by jbjarn17** [comment]
Issue #66 (branch feature_66) uses an API call to create a citizen.
This happens in new_citizen_bloc.dart in method createCitizen() and in initialize().

Just a heads up, so we know where API happens.
No attempt has been made to catch the API exception because it was not testable.

**Comment by Laexander** [comment]
This issue was hard to estimate as what the problem is, isn't clear. The immidiate intution from the estimation group is it will take a lot of time to find the exact error but the fix won't take as long

**Comment by joandrsn** [comment]
Okay looking into this, I don't see this as an issue.
The problem is that since the login functionality is async, the response might come at a much later time. If we were to use `try`-`catch`, the UI would have to hold until the response was returned.

Instead, we should look more into how streams work.
If you were to instead provide an `onError` option for the `listen` function, you can catch the exception as you wanted.
And on top of that, the UI doesn't have to wait until the exception is thrown.
In this example, I provide an `onError`-function which is called by the internals of the `listen` function.
![image](https://user-images.githubusercontent.com/5766695/79869063-22073780-83e1-11ea-8e12-4db2b9f5969b.png)
And the result (when logging in with invalid credentials):
![image](https://user-images.githubusercontent.com/5766695/79869078-2895af00-83e1-11ea-91ae-733d9af93ac6.png)

Further reading:
https://api.flutter.dev/flutter/dart-async/Stream/listen.html
The interesting bit is the following:
_If  `onError` is omitted, any errors on this stream are considered unhandled, and will be passed to the current Zone's error handler. By default unhandled async errors are treated as if they were uncaught top-level errors._

**Comment by joandrsn** [comment]
Upon further talks with group 15, it appears that the problem is instead in this function:
https://github.com/aau-giraf/weekplanner/blob/b4b22a9fd23cfc2f7c897c80f8f62bccf3968b5e/lib/blocs/new_citizen_bloc.dart#L65-L73
In this function, one should simply do the same as above.
Instead of directly forwarding the actual API call to the UI (Which I believe is a violation of the BLoC pattern), handle the response in the BLoC, and forward it to another topic in the bloc.

![image](https://user-images.githubusercontent.com/5766695/79963811-23d90580-848a-11ea-8adf-fedca4963a74.png)

![image](https://user-images.githubusercontent.com/5766695/79964215-acf03c80-848a-11ea-9175-176c103f9762.png)

**Comment by joandrsn** [comment]
After discussing further with group 15, this issue can be closed
