### ISSUE TITLE
As a developer, i would like to have Error handling when doing API calls from BloCs, as to make the weekplanner more responsive

### ISSUE THREAD

**Issue by Rsvend17** [aau-giraf/weekplanner-OLDUI#431]
**Is your feature request related to a problem? Please describe.**
As of now A lot of the BloCs are not handling exceptions/errors thrown when doing an API call. 
This should be handled, and the response should be sent to the screen, with a response message to that error. 
This is now possible, regarding https://github.com/aau-giraf/weekplanner/issues/349. ( is in a comment)
This would make the App better, as it is more responsive when doing requests. 

**Describe the solution you'd like**
I would like to have whoever is on this issue, to create other issues as https://github.com/aau-giraf/weekplanner/issues/429, https://github.com/aau-giraf/weekplanner/issues/428 to all the places, where API calls are made, but no error/Exception handling is made.

**Describe alternatives you've considered**
I do not consider any alternative solutions. Error handling is Perile for a good application.

**Comment by Lortemanden** [comment]
The problem is that since the login functionality is async, the response might come at a much later time. If we were to use `try`-`catch`, the UI would have to hold until the response was returned.

Instead, we should look more into how streams work.
If you were to instead provide an `onError` option for the `listen` function, you can catch the exception as you wanted.
And on top of that, the UI doesn't have to wait until the exception is thrown.
In this example, I provide an `onError`-function which is called by the internals of the `listen` function.
![image](https://user-images.githubusercontent.com/5766695/79869063-22073780-83e1-11ea-8e12-4db2b9f5969b.png)
And the result (when logging in with invalid credentials):
![image](https://user-images.githubusercontent.com/5766695/79869078-2895af00-83e1-11ea-91ae-733d9af93ac6.png)

Further reading:
https://api.flutter.dev/flutter/dart-async/Stream/listen.html
The interesting bit is the following:
_If  `onError` is omitted, any errors on this stream are considered unhandled, and will be passed to the current Zone's error handler. By default unhandled async errors are treated as if they were uncaught top-level errors._

**Comment by Mustafa-ALD** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 431](https://trello.com/c/7rzoqE5c/27-issue-431)

**Comment by Mustafa-ALD** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 431](https://trello.com/c/7rzoqE5c/27-issue-431)

**Comment by Mustafa-ALD** [comment]
Found one place where error/exception handling is missing. (#597 )

Will keep on searching for more

Update: issues
#604 
#605 
#607 
#608 
#610 
#612 
#613 
#614 
has been created

**Comment by Kaliahh** [comment]
To complete this issue, all linked issues must be completed first

**Comment by JeppeKLau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 431](https://trello.com/c/4wt05BQt/49-issue-431)
