### ISSUE TITLE
As a user I would like an indication for when I can scroll in the days in the weekplan

### ISSUE THREAD

**Issue by tuanvu29** [aau-giraf/weekplanner-OLDUI#526]
**Is your feature request related to a problem? Please describe.**
It is hard to see if there are more activities for the day then the onces shown because not all activities can be shown. Especially when I have the "Fjern aktiviteten" enabled, so it seems like the day is empty. 

**Describe the solution you'd like**
I would like to see an indication that I can scroll on the day column for when the weekplan does not show all the activities for that day. See comment below for prototypes.

**Comment by dkalaxdk** [comment]
When a row in the weekplan is scrollable, it should be shown by having the top and bottom defined by a white edge as seen in the image.
The color of the edge should be easy to change, as it might become an option at a later date to choose the color of the highlighting. 

For citizens:
![2020e_3_C_CIT_1_WP526 Scrolling in weekplan](https://user-images.githubusercontent.com/13720707/97312596-f3718a00-1865-11eb-91cb-34b033638480.png)

For guardians:
![2020e_3_B_GUA_1_WP526 Scrolling in weekplan](https://user-images.githubusercontent.com/42242841/97425925-0c844480-1913-11eb-827a-b9626b942b75.png)

For guardians in edit mode:
![2020e_3_A_GUA_1_WP526 Scrolling in weekplan edit mode](https://user-images.githubusercontent.com/42242841/97425956-160dac80-1913-11eb-89ea-fb31308dec1c.png)

**Comment by JeppeKLau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 526](https://trello.com/c/OSkuYO4g/57-issue-526)

**Comment by Mustafa-ALD** [comment]
There is created a branch (feature/526) for this issue.

The first thing that has been created is a gradient that is behind the elements, the gradient goes from white to transparent and then to white. There are two transparent colors to make it prettier.
https://github.com/aau-giraf/weekplanner/blob/82c16a13fb34da01ca6098bd36f5e437c08bc108/lib/widgets/weekplan_screen_widgets/weekplan_day_column.dart#L222-L231
This is how it will look like.
![image](https://user-images.githubusercontent.com/43955099/100991754-a747f280-3553-11eb-8b15-555517cee83a.png)

The other thing that has been added is a notifier that makes it possible to know when the user has scrolled to the top and bottom. 
There are three if statements:
1. The first if statement checks if the scoll is at the bottom
2. The second if statement checks if the scroll is at the top
3. The third if statement checks if the scroll is both on top and bottom
(The third if statements has not been checked if it works, but the other two has been checked with prints)
https://github.com/aau-giraf/weekplanner/blob/82c16a13fb34da01ca6098bd36f5e437c08bc108/lib/widgets/weekplan_screen_widgets/weekplan_day_column.dart#L270-L297
This is an example if the user scrolls to the bottom.
![image](https://user-images.githubusercontent.com/43955099/100992849-f5112a80-3554-11eb-8057-f088e99c6580.png)

**What the next developer should do:**
You should connect these two features together so that they communicate.
We have tried changing the values of the gradient through the notifier (second feature), but the gradient (first feature) won't change color because it has to be updated. And to do that we have to use a stateful widget, since this is built on a stateless widget we couldn't just update the information or just update the widget. We would have to update the whole screen which might reset the scrolling (which would send the scrolling back to the top).

We have also tried making the whole class stateful, but that broke the screen and the columns became red and had error messages on them.

Maybe try and create a new stateful class, where the columns can be created and update without disturbing the other widgets.
