### ISSUE TITLE
As a guardian I would like to update the settings for a given citizen so that it fits their preference in terms in colors

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#64]

**Comment by sipman** [comment]
This feature has three main tasks:
- Make the settings screen reflect the options available
- Make a BLoC which has the responsibility of delegating the data
- Ensure that the API component allows sending the citizen id and not only the authenticated id
- Make the weekplan-screen reflect the chosen option.

**Comment by sipman** [comment]
This task could be "conflicting" with the #65 story. Please address if neccessary

**Comment by Lortemanden** [comment]
This is a old issue so the three main tasks mentioned above might already have been solved by other issues. 
The settings page shown below should already be implemented. 
![image](https://user-images.githubusercontent.com/55434783/77544178-fad44d80-6ea8-11ea-9f30-b202e70d1cc0.png)
When pressing the "Farver på ugeplan" it should take you to the screen shown below. On this screen it should be possible to chose between the shown colour standards. When making the colour standards be aware that there will be another issue about making the guardian able to make their own.
![image](https://user-images.githubusercontent.com/55434783/77543953-ab8e1d00-6ea8-11ea-9665-3708d33b0443.png)
A example of the weekplanner with the grå/hvid colour theme can be seen below. The blå/hvid is the same with blue instead of gray.
![image](https://user-images.githubusercontent.com/55434783/77544520-64545c00-6ea9-11ea-985e-dc5c36d393d0.png)
