### ISSUE TITLE
As a Guardian or Trustee I would like the confirmation buttons to be switch when I change want to Citizen view

### ISSUE THREAD

**Issue by Dieuer** [aau-giraf/weekplanner-OLDUI#837]
In the weekplanner when changing from Guardian/Citizen or trustee/citizen the buttons presented in the popup should be switched, as the confirmation button always should be on the left in order for better UX.

**Comment by Bisgaard01** [comment]
Ambiguous user story. As I understand it should swap the position of the cancel and accept buttons in only this instance, but then this would be different from the order of all other cancel and accept buttons, leading to worse UX (unless changed for all). 

Is this something the stakeholders have requested? This issue is closed unless this is the case.
